apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    app: cart
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
      project: roboshop
      tier: backend
  template:
    metadata:
      labels:
        app: cart
        project: roboshop
        tier: backend
    spec:
      containers:
      - name: cart
        image: madashrithik/cart:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis.roboshop.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    app: cart
    project: roboshop
    tier: backend
  ports:
  - protocol: TCP
    port: 8080       # service port
    targetPort: 8080 # container port
