apiVersion: v1
kind: ConfigMap
metadata:
  name: cata
  namespace: roboshop
data:
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cata
  namespace: roboshop
  labels: # these labels are deployment labels
    app: cata
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: cata
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: cata
        project: roboshop
        tier: app
    spec:
      containers:
      - name: cata
        image: madashrithik/cata:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cata
---
apiVersion: v1
kind: Service
metadata:
  name: cata
  namespace: roboshop
spec:
  selector:
    app: cata
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port