apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: madashrithik/web:v1       # or roboshop/web:latest if available
        ports:
        - containerPort: 80
        env:
        - name: CATALOGUE_HOST
          value: "catalogue"
        - name: CATALOGUE_PORT
          value: "8080"
        - name: USER_HOST
          value: "user"
        - name: USER_PORT
          value: "8080"
        - name: CART_HOST
          value: "cart"
        - name: CART_PORT
          value: "8080"
        - name: SHIPPING_HOST
          value: "shipping"
        - name: SHIPPING_PORT
          value: "8080"
        - name: PAYMENT_HOST
          value: "payment"
        - name: PAYMENT_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
